
import { GoogleGenAI, GenerateContentResponse } from "@google/genai";
import { GenerationConfig, SubjectType, Style } from "../types";

export class GeminiService {
  private ai: GoogleGenAI;

  constructor() {
    this.ai = new GoogleGenAI({ apiKey: process.env.API_KEY || '' });
  }

  public async generateProductContent(config: GenerationConfig): Promise<string> {
    const prompt = this.buildPrompt(config);
    const parts: any[] = [{ text: prompt }];

    if (config.productImage) {
      parts.push({
        inlineData: {
          data: config.productImage.split(',')[1],
          mimeType: 'image/png'
        }
      });
    }

    if (config.backgroundImage) {
      parts.push({
        inlineData: {
          data: config.backgroundImage.split(',')[1],
          mimeType: 'image/png'
        }
      });
    }

    try {
      const response: GenerateContentResponse = await this.ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: { parts },
        config: {
          imageConfig: {
            aspectRatio: this.mapRatio(config.ratio)
          }
        }
      });

      let imageUrl = '';
      if (response.candidates?.[0]?.content?.parts) {
        for (const part of response.candidates[0].content.parts) {
          if (part.inlineData) {
            imageUrl = `data:image/png;base64,${part.inlineData.data}`;
            break;
          }
        }
      }

      if (!imageUrl) throw new Error("No image generated by AI");
      return imageUrl;
    } catch (error) {
      console.error("Gemini Generation Error:", error);
      throw error;
    }
  }

  private buildPrompt(config: GenerationConfig): string {
    const subjectDesc = this.getSubjectDescription(config);
    const styleDesc = this.getStyleDescription(config.style);
    
    let prompt = `Create a high-quality, professional affiliate marketing image.
    The main product is shown in the first image part.
    Subject Style: ${subjectDesc}.
    Overall Aesthetic: ${styleDesc}.
    ${config.backgroundImage ? "Use the provided background reference image for environment inspiration." : "Place the product in an appropriate aesthetic environment."}
    ${config.additionalPrompt ? `Additional Details: ${config.additionalPrompt}` : ""}
    ${config.branding ? `Subtly include the text watermark "${config.branding}" in the corner as if it was part of a brand shoot.` : ""}
    The final image should be clean, commercial-grade, and without any system watermarks.`;

    return prompt;
  }

  private getSubjectDescription(config: GenerationConfig): string {
    const gender = config.gender ? `a ${config.gender.toLowerCase()} model` : "a model";
    switch (config.subjectType) {
      case SubjectType.ProductOnly: return "Focus solely on the product, clean and high-end studio lighting";
      case SubjectType.Handheld: return `The product being held naturally by ${gender}'s hand`;
      case SubjectType.FullModel: return `A full professional model (${gender}) interacting with or wearing the product in a stylish pose`;
      case SubjectType.POV: return `Point-of-view perspective, as if seen through someone's eyes while using the product`;
      default: return "Clean product presentation";
    }
  }

  private getStyleDescription(style: Style): string {
    switch (style) {
      case Style.Retro: return "Vintage film look, warm tones, slight grain, classic photography style";
      case Style.SoftAesthetic: return "Dreamy, pastel colors, soft lighting, minimal shadows, very clean and airy";
      case Style.Fancy: return "Luxury, high contrast, glossy surfaces, premium lighting, sophisticated mood";
      default: return "Modern and clean";
    }
  }

  private mapRatio(ratio: string): "1:1" | "3:4" | "4:3" | "9:16" | "16:9" {
    if (["1:1", "3:4", "4:3", "9:16", "16:9"].includes(ratio)) {
      return ratio as any;
    }
    return "1:1";
  }
}
